{% set version = "1.4.0" %}

package:
  name: bokeh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bokeh/bokeh-{{ version }}.tar.gz
  sha256: c60d38a41a777b8147ee4134e6142cea8026b5eebf48149e370c44689869dce7

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
    - find {{ PREFIX }} -name '*.js.map' -delete  # [not win]
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.7
    - numpy >=1.7.1
    - packaging >=16.8
    - pillow >=4.0
    - python-dateutil >=2.1
    - pyyaml >=3.10
    - six >=1.5.2
    - tornado >=4.3
    - futures >=3.0.3  # [py27]

test:
  requires:
    - pip
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.property
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.sampledata
    - bokeh.server
    - bokeh.protocol
    - bokeh.protocol.messages
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util
  commands:
    - pip check
    - bokeh --help

about:
  home: http://bokeh.pydata.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Statistical and novel interactive HTML plots for Python
  description: |
    Bokeh is a Python interactive visualization library that targets
    modern web browsers for presentation. Its goal is to provide elegant,
    concise  construction of novel graphics in the style of D3.js, and to
    extend this capability with high-performance interactivity over very
    large or streaming datasets. Bokeh can help anyone who would like to
    quickly and easily create interactive plots, dashboards, and data
    applications.
  doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
  dev_url: http://github.com/bokeh/bokeh

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
    - ocefpaf
