{% set version = "2.4.0" %}

package:
  name: bokeh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bokeh/bokeh-{{ version }}.tar.gz
  sha256: 6fa00ed8baab5cca33f4175792c309fa2536eaae7e90abee884501ba8c90fddb

build:
  number: 0
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.9
    - numpy >=1.11.3
    - packaging >=16.8
    - pillow >=7.1.0
    - pyyaml >=3.10
    - tornado >=5.1
    - typing_extensions >=3.10.0

test:
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.property
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.sampledata
    - bokeh.server
    - bokeh.protocol
    - bokeh.protocol.messages
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util
  commands:
    - pip check
    - bokeh --help
  requires:
    - pip

about:
  home: http://bokeh.pydata.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Statistical and novel interactive HTML plots for Python
  description: |
    Bokeh is a Python interactive visualization library that targets
    modern web browsers for presentation. Its goal is to provide elegant,
    concise  construction of novel graphics in the style of D3.js, and to
    extend this capability with high-performance interactivity over very
    large or streaming datasets. Bokeh can help anyone who would like to
    quickly and easily create interactive plots, dashboards, and data
    applications.
  doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
  dev_url: http://github.com/bokeh/bokeh

extra:
  recipe-maintainers:
    - almarklein
    - jakirkham
    - mattpap
    - ocefpaf
    - philippjfr
